### ISSUE TITLE
Go through post-branch PRs on GPflow 1

### ISSUE THREAD

**Issue by st--** [GPflow/GPflow#1215]
The gpflow2 code (now `develop`) was branched off the old develop (now `develop-1.0`) a while ago, and PRs into GPflow 1 after this branch-off point may or may not have found their way into gpflow2. We should go through all these PRs and double-check we aren't missing any improvements in gpflow2.

PRs that got merged into develop-1.0 following the split with develop(-2.0):

- [X] #827 (cleaning up stationary kernel implementations to only require `K_r` or `K_r2`): done in #1088 
- [x] #829 (support broadcasting): see #1308
- [ ] #830 (MixedKernelSeparateMof): @JoshuaAlbert - see #1380 
- [ ] #754 (cross-covariance of SquaredExponential in expectations framework): confirmed missing - see #1333 
- [x] ~#840 (fix slice active_dims): not an issue in gpflow2~
- [X] #836 (sample_conditional also returns mean and cov and supports num_samples>1)
- [X] #859 (clean up GPR docstring)
- [X] #879 (compute q(u) in SGPR)
- [X] #909 (fix models maths documentation)
- [X] #895 (Broadcasting of conditionals): see #1308
- [X] #933 (performance improvement: gauss_kl can take K_cholesky directly): see #1306
- [x] #957 (SwitchedLikelihood workaround): see #1316
- [ ] #973 (change 1e-40 threshold to 1e-36): confirmed missing - @markvdw what was this change for?
- [x] #1000 (kernel broadcasting tests & documentation): see #1308
- [x] contributing.md is out of date - see #1326

**Comment by st--** [comment]
#1218 is related to this

**Comment by st--** [comment]
The two remaining issues have been moved to #1380 and #1333
