### ISSUE TITLE
Missing documentations (template issue to list things related to documentation that are missing)

### ISSUE THREAD

**Issue by yiwei-prowler** [GPflow/GPflow#1252]
- [x] ~The method GPR.predict_f is missing return type annotation -> MeanAndVariance.~ see #1346 
- [x] The method GPModel.predict_log_density is missing documentation for its parameters, returned value, and is missing the returned type. It also needs shape assertions for its return type.
- [x] The method GPR.log_likelihood is missing returned type annotation.
- [x] ~SVGP.predict_f says its return type is tf.Tensor, but its ancester method says the returned type is MeanAndVariance, which is a tuple. These two types are not compatable.~ see #1346 
- [x] ~SVGP.log_likelihood declares its argument data to have type Tuple[tf.Tensor, tf.Tensor], but there are many places that use the type alias Data, this is confusing. Don't know where should each be used -- I'm working on warping support, and don't know when referencing to data, which type I should use.~ see #1346 
- [x] BayesianModel.log_prior, its comment is missing, the shape of its return value is missing.
- [x] BayesianModel.log_marginal_likelihood, its comment is missing, the shape of its return type is missing..
- [x] BayesianModel.log_likelihood, its comment is missing, the shape of its return type is missing.
- [x] ~GPR.predict_f_samples. The parameter full_cov: bool = True indicates that its value can be either True of False. But try it with False crashes.~ see #1327

**Comment by st--** [comment]
@yiwei-prowler it would be great if you could help us out and contribute this simple fix as a PR. thank you!

**Comment by joelberkeley** [comment]
@yiwei-prowler i can do this if you like. more generally, I don't think we should assert shapes on anything but arguments - that responsibility lies with the tests

**Comment by st--** [comment]
As far as I can tell most of this has actually happened along the way in #1276 and other PRs.
